project_id = "iaaildgwlzywzydgsjwo"

[functions.create-organization]
verify_jwt = false

[functions.update-admin-password]
verify_jwt = false

[functions.crm-ai]
verify_jwt = false

[functions.manage-org-users]
verify_jwt = false

[functions.send-test-email]
verify_jwt = false

[functions.send-scheduled-messages]
verify_jwt = false
crons = ["*/5 * * * *"]

[functions.process-scheduled-messages]
crons = ["*/5 * * * *"]
